Resources:
  #TobyVPC:
  #  Type: 'AWS::EC2::VPC'
  #  Properties:
  #    CidrBlock: 10.0.0.0/24
  #    EnableDnsHostnames: 'true'
  #    Tags:
  #      - Key: Name
  #        Value: CiCdStack

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: UdacityKey
      InstanceType: t2.micro
      ImageId: 'ami-09e67e426f25ce0d7' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
  
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      #VpcId: !Ref TobyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0